apiVersion: v1
kind: Pod
metadata:
  name: digest-only-all-container-types
  namespace: default
spec:
  containers:
    - name: regular-digest-only
      image: host:5000/team/app@sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
  initContainers:
    - name: init-digest-only
      image: host:5000/team/app@sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
  ephemeralContainers:
    - name: ephemeral-digest-only
      image: host:5000/team/app@sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
